# k8s-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-metrics-collector
  namespace: redis-monitoring
spec:
  schedule: "*/1 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redis-metrics
            image: docker.io/owenmurphy2022v1/redis-metrics:latest # Replace with your docker image
            imagePullPolicy: IfNotPresent
            env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: redis-url
            - name: REDIS_CERT_PATH
              value: /etc/redis-cert/redis.crt # or whatever the cert file is called.
            volumeMounts:
            - name: redis-cert
              mountPath: /etc/redis-cert
          volumes:
          - name: redis-cert
            secret:
              secretName: redis # Name of the secret containing the redis certificate
          restartPolicy: OnFailure
