# k8s-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-metrics-collector
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redis-metrics
            image: docker.io/owenmurphy2022v1/redis-metrics # Replace with your docker image
            args:
            - "--redis-url=$(REDIS_URL)"
            - "--redis-cert-path=/etc/redis-cert/redis.crt"
            env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: redis-url
            volumeMounts:
            - name: redis-cert
              mountPath: /etc/redis-cert
          volumes:
          - name: redis-cert
            secret:
              secretName: redis # Name of the secret containing the redis certificate
          restartPolicy: OnFailure
      restartPolicy: OnFailure
